name: Expenses

on:
  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest  # Use GitHub-hosted runners for simplicity

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements_docker.txt ]; then pip install -r requirements_docker.txt; fi

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t medical .
          docker tag medical sharanrh/medical:latest

      - name: Push Docker Image
        run: |
          docker push sharanrh/medical:latest
