# name: Expenses

# on:
#   push:
#     branches: [ "main" ]
#   pull_request: 
#     branches: [ "main" ]

# permissions:
#   contents: read

# jobs:
#   build:
#     runs-on: [ ubuntu-latest ]  #self-hosted

#     steps:
#       - uses: actions/checkout@v3

#       - name: Set Up Python 3.12
#         uses: actions/setup-python@v2
#         with:
#           python-version: "3.12"

#       - name: Install Dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install flake8 pytest
#           if [ -f requirements_docker.txt ]; then pip install -r requirements_docker.txt; fi

#       - name: Docker Build and Push to Docker Hub
#         run: |
#          docker build -t medical .
#          docker tag medical sharanrh/medical:latest
#          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
#          docker push sharanrh/medical:latest
#         env:
#           DOCKER_CLI_ACI: 1


name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t medical .
          docker tag medical sharanrh/medical:latest


      - name: Push Docker image
        run: |
          docker push sharanrh/medical:latest
